package com.dev.exception;

public class ExceptionHandling {

	public static void main(String[] args)throws CustomException {
		try {
			s();
			System.out.println("No Exception for s()");
			int res = divide(10,0);
			System.out.println("No exception for divide()");
			
		}
		

	}

}
